name: slim-minimal-website
type: php
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: ['minimal-website.slim.test']
database:
  type: mariadb
  version: "10.11"
omit_containers: [db]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "18"
corepack_enable: false
disable_upload_dirs_warning: true
